"""autogenerate

Revision ID: ce466fbd1dd4
Revises: 001_initial
Create Date: 2026-05-21 17:45:59.241852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce466fbd1dd4'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultation_applications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='applicationstatus'),
               nullable=False)
    op.alter_column('consultation_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_favorites_user'), table_name='favorites')
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_work_id'), 'favorites', ['work_id'], unique=False)
    op.drop_index(op.f('idx_likes_work_id'), table_name='likes')
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_likes_work_id'), 'likes', ['work_id'], unique=False)
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_subscriptions_master'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_master_id'), 'subscriptions', ['master_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriber_id'), 'subscriptions', ['subscriber_id'], unique=False)
    op.drop_index(op.f('idx_tags_name_trgm'), table_name='tags', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_index(op.f('idx_tattoo_works_created'), table_name='tattoo_works')
    op.drop_index(op.f('idx_tattoo_works_likes'), table_name='tattoo_works')
    op.drop_index(op.f('idx_tattoo_works_master'), table_name='tattoo_works')
    op.drop_index(op.f('idx_tattoo_works_status'), table_name='tattoo_works')
    op.create_index(op.f('ix_work_reviews_id'), 'work_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_work_reviews_work_id'), 'work_reviews', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_reviews_work_id'), table_name='work_reviews')
    op.drop_index(op.f('ix_work_reviews_id'), table_name='work_reviews')
    op.create_index(op.f('idx_tattoo_works_status'), 'tattoo_works', ['status'], unique=False)
    op.create_index(op.f('idx_tattoo_works_master'), 'tattoo_works', ['master_id'], unique=False)
    op.create_index(op.f('idx_tattoo_works_likes'), 'tattoo_works', [sa.literal_column('like_count DESC')], unique=False)
    op.create_index(op.f('idx_tattoo_works_created'), 'tattoo_works', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tags_name_trgm'), 'tags', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_subscriptions_subscriber_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_master_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.create_index(op.f('idx_subscriptions_master'), 'subscriptions', ['master_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_likes_work_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.create_index(op.f('idx_likes_work_id'), 'likes', ['work_id'], unique=False)
    op.drop_index(op.f('ix_favorites_work_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.create_index(op.f('idx_favorites_user'), 'favorites', ['user_id'], unique=False)
    op.alter_column('consultation_applications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('consultation_applications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='applicationstatus'),
               nullable=True)
    # ### end Alembic commands ###
